/**
 * services/Theming.ts
 * Matugen color pipeline.
 *
 * Flow:
 *   1. applyTheme(wallpaperPath?) called on start or wallpaper change
 *   2. Runs matugen to generate palette JSON
 *   3. Transforms palette → CSS custom properties
 *   4. Writes styles/tokens.css
 *   5. AGS reloads CSS hot — no shell restart needed
 */

import { execAsync, subprocess } from "astal/process"
import { writeFileSync, readFile } from "astal/file"
import { App } from "astal/gtk4"
import GLib from "gi://GLib"
import { getConfig } from "./Config"

// ── Types ─────────────────────────────────────────────────────────────────────

interface MatugenColor {
  hex: string
  hct: { hue: number; chroma: number; tone: number }
}

interface MatugenPalette {
  colors: {
    // Core roles
    primary:                MatugenColor
    on_primary:             MatugenColor
    primary_container:      MatugenColor
    on_primary_container:   MatugenColor
    secondary:              MatugenColor
    on_secondary:           MatugenColor
    secondary_container:    MatugenColor
    on_secondary_container: MatugenColor
    tertiary:               MatugenColor
    on_tertiary:            MatugenColor
    background:             MatugenColor
    on_background:          MatugenColor
    surface:                MatugenColor
    on_surface:             MatugenColor
    surface_variant:        MatugenColor
    on_surface_variant:     MatugenColor
    outline:                MatugenColor
    outline_variant:        MatugenColor
    error:                  MatugenColor
    on_error:               MatugenColor
  }
}

// ── Cache path ─────────────────────────────────────────────────────────────────
const CACHE_DIR    = `${GLib.get_user_cache_dir()}/axdots`
const PALETTE_PATH = `${CACHE_DIR}/palette.json`
const TOKENS_PATH  = `${App.configDir}/styles/tokens.css`

// ── Main export ────────────────────────────────────────────────────────────────

export async function applyTheme(wallpaperPath?: string): Promise<void> {
  const cfg = getConfig()
  const wall = wallpaperPath ?? cfg.theme.wallpaper

  console.log("[Theme] Running matugen for:", wall)

  try {
    // Ensure cache dir exists
    await execAsync(["mkdir", "-p", CACHE_DIR])

    // Run matugen — generates palette JSON
    await execAsync([
      "matugen",
      "image",
      wall,
      "--type", cfg.theme.matugenScheme,
      "--format", "json",
      "--json", "hex",
      "-o", PALETTE_PATH,
    ])

    const raw = readFile(PALETTE_PATH)
    const palette: MatugenPalette = JSON.parse(raw)

    const css = buildCssTokens(palette, wall)
    writeFileSync(TOKENS_PATH, css)

    // Hot-reload CSS in running AGS instance
    App.resetCss(`${App.configDir}/styles/main.css`)
    console.log("[Theme] Tokens rebuilt & CSS reloaded ✦")
  } catch (e) {
    console.error("[Theme] Failed to apply theme:", e)
    // Write fallback dark tokens so shell doesn't break
    writeFileSync(TOKENS_PATH, FALLBACK_TOKENS)
    App.resetCss(`${App.configDir}/styles/main.css`)
  }
}

// ── CSS token builder ──────────────────────────────────────────────────────────

function hex2rgba(hex: string, alpha: number): string {
  const r = parseInt(hex.slice(1, 3), 16)
  const g = parseInt(hex.slice(3, 5), 16)
  const b = parseInt(hex.slice(5, 7), 16)
  return `rgba(${r},${g},${b},${alpha})`
}

function buildCssTokens(p: MatugenPalette, wallPath: string): string {
  const c = p.colors

  // Derive extra values from palette
  const bgHex  = c.background.hex
  const surfHex = c.surface_variant.hex

  return `/* axdots — Auto-generated by matugen — DO NOT EDIT */
/* Source wallpaper: ${wallPath} */
/* Generated: ${new Date().toISOString()} */

@define-color bg            ${bgHex};
@define-color bg_blur       ${hex2rgba(bgHex, 0.15)};
@define-color bg_solid      ${hex2rgba(bgHex, 0.92)};
@define-color surface       ${c.surface.hex};
@define-color surface_blur  ${hex2rgba(surfHex, 0.12)};
@define-color surface_var   ${c.surface_variant.hex};
@define-color primary       ${c.primary.hex};
@define-color on_primary    ${c.on_primary.hex};
@define-color primary_cont  ${c.primary_container.hex};
@define-color secondary     ${c.secondary.hex};
@define-color tertiary      ${c.tertiary.hex};
@define-color on_surface    ${c.on_surface.hex};
@define-color on_surf_var   ${c.on_surface_variant.hex};
@define-color text          ${c.on_background.hex};
@define-color text_muted    ${c.on_surface_variant.hex};
@define-color outline       ${c.outline.hex};
@define-color outline_var   ${c.outline_variant.hex};
@define-color error         ${c.error.hex};

/* Semantic glass tokens */
@define-color glass_bg      ${hex2rgba(bgHex, 0.14)};
@define-color glass_border  ${hex2rgba(c.outline_variant.hex, 0.30)};
@define-color glass_hover   ${hex2rgba(c.on_surface.hex, 0.06)};
@define-color glass_active  ${hex2rgba(c.on_surface.hex, 0.03)};
@define-color accent        ${c.primary.hex};
@define-color accent_soft   ${hex2rgba(c.primary.hex, 0.15)};

/* Derived notification colors (fixed roles) */
@define-color notif_low     ${c.secondary.hex};
@define-color notif_normal  ${c.primary.hex};
@define-color notif_critical ${c.error.hex};
`
}

// ── Fallback for when matugen isn't installed ──────────────────────────────────

const FALLBACK_TOKENS = `/* axdots — fallback dark tokens (matugen unavailable) */
@define-color bg            #0d1117;
@define-color bg_blur       rgba(13,17,23,0.15);
@define-color bg_solid      rgba(13,17,23,0.92);
@define-color surface       #161b22;
@define-color surface_blur  rgba(22,27,34,0.12);
@define-color surface_var   #21262d;
@define-color primary       #58a6ff;
@define-color on_primary    #0d1b30;
@define-color primary_cont  #1d3557;
@define-color secondary     #7ee787;
@define-color tertiary      #e3b341;
@define-color on_surface    #e6edf3;
@define-color on_surf_var   #8b949e;
@define-color text          #c9d1d9;
@define-color text_muted    #8b949e;
@define-color outline       #30363d;
@define-color outline_var   #21262d;
@define-color error         #f97583;
@define-color glass_bg      rgba(13,17,23,0.14);
@define-color glass_border  rgba(48,54,61,0.30);
@define-color glass_hover   rgba(230,237,243,0.06);
@define-color glass_active  rgba(230,237,243,0.03);
@define-color accent        #58a6ff;
@define-color accent_soft   rgba(88,166,255,0.15);
@define-color notif_low     #7ee787;
@define-color notif_normal  #58a6ff;
@define-color notif_critical #f97583;
`
